apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-path
          name: pv-1
  volumes:
    - name: pv-1
      persistentVolumeClaim:
        claimName: pvc-1
