apiVersion: v1
kind: Pod
metadata:
  name: pod-vol
  labels:
    app: pod-vol
spec:
  containers:
    - name: pod-vol-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /first-volume
          name: pod-vol-volume
      ports:
        - containerPort: 80
  volumes:
    - name: pod-vol-volume
      hostPath:
        path: /C/teste/
        type: DirectoryOrCreate