apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-system-deployment
spec:
  template:
    metadata:
      name: news-system-pod
      labels:
        app: news-system
    spec:
      containers:
        - name: news-system-container
          image: nginx:stable
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: news-system-configmap
  replicas: 3
  selector:
    matchLabels:
      app: news-system