apiVersion: v1
kind: Pod
metadata:
  name: news-db
  labels:
    app: news-db
spec:
  containers:
    - name: news-db-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: cm-news-db

      # env:
      #   - name: MYSQL_DATABASE
      #     valueFrom:
      #       configMapKeyRef:
      #         key: MYSQL_DATABASE
      #         name: cm-news-db

      # env:
      #   - name: MYSQL_DATABASE
      #     value: empresa
